version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "03:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: semantic-release
    versions:
    - 17.4.0
    - 17.4.1
  - dependency-name: tape
    versions:
    - 5.1.1
    - 5.2.0
    - 5.2.1
