language: node_js

node_js:
  - "10"
  - "8"
  - "6"
  - "5"

env:
  - EXIST_DB_VERSION=eXist-5.0.0-rc1
  - EXIST_DB_VERSION=eXist-4.2.1
  - EXIST_DB_VERSION=eXist-3.6.1
  - EXIST_DB_VERSION=eXist-2.2

addons:
  apt:
    packages:
      - oracle-java8-installer

sudo: false

notifications:
  email: false

before_install:
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle

install:
  - ci/setup.sh
  - npm install -q

before_script:
  - nohup ${HOME}/exist/${EXIST_DB_VERSION}/bin/startup.sh &
  - npm prune
  - curl -Lo travis_after_all.py https://git.io/vLSON
  - sleep 30
  - curl http://127.0.0.1:8080/exist

script:
  - npm test

after_success:
  - python travis_after_all.py
  - npm run semantic-release

after_script:
  - $HOME/exist/${EXIST_DB_VERSION}/bin/shutdown.sh

before_cache:
  - ci/teardown.sh

cache:
  directories:
    - node_modules
    - ${HOME}/exist
