version: 1.2.{build}

environment:
  NODE_VERSION: 12

  matrix:
  - EXIST_VERSION: 5.0.0-RC4
  - EXIST_VERSION: 4.7.1

install:
  - ps: Install-Product node $env:NODE_VERSION
  - cmd: npm install
  - ps: ./ci/setup.ps1

test_script:
  - cmd: npm test

after_test:
  - ps: ./ci/teardown.ps1

cache:
  - C:\build
  - node_modules

build: off
