name: "Setup eXist-db"
description: "Start an exist-db instance running in a docker container"
inputs:
  docker-tag:
    description: "Tag of the existdb docker"
    required: true
    default: "release"

runs:
  using: "composite"
  steps:
    - id: setup
      run: |
        docker pull existdb/existdb:${{ inputs.docker-tag }}
        docker create --name exist-ci -p 8080:8080 -p 8443:8443 existdb/existdb:${{ inputs.docker-tag }}
        docker start exist-ci
      shell: bash
      # TODO this should rather be polling for a running container / a running service
    - id: wait-to-exist
      run: sleep 30
      shell: bash
