name: Release npm package

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: npm install and build
        run:
          npm ci

      - name: Pull docker image
        run: docker pull existdb/existdb:release

      - name: Build docker image
        run: docker create --name exist-ci -p 8080:8080 -p 8443:8443 existdb/existdb:release

      - name: Start docker image
        run: docker start exist-ci

      - name: Wait for existdb startup
        run: sleep 30

      - run: npm test
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}