name: test node-exist

on:
  pull_request:
    branches: [ master, develop ]

  push:
    branches:
      - develop

  workflow_dispatch:

jobs:
  build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [10.x, 12.x, 14.x]
          docker-tag: [latest, release, 4.7.1]
      steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install and build
        run: npm ci

      - name: Pull docker image
        run: docker pull existdb/existdb:${{ matrix.docker-tag }}

      - name: Build docker image
        run: docker create --name exist-ci -p 8080:8080 -p 8443:8443 existdb/existdb:${{ matrix.docker-tag }}

      - name: Start docker image
        run: docker start exist-ci

      - name: Wait for existdb startup
        run: sleep 30

      - name: npm test
        run: npm test